"""
Django settings for quest project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b32!1qbclcwo2$bfj-ma29k5^-%iy)dh$&h95=0+c7wy^!8+ft'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Journey'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'quest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'quest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    
 ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#STRIPE_PUBLIC_KEY = 'pk_test_51PfWtRFJxUP3SBN9C7YE2De9GZPqhJohMeGk0hQLPn3T3QowOS6qayoMtrsG50HHRuhCZhSu4wdsuEHsVtytp3Ds00RNBnMqsw'
#STRIPE_SECRET_KEY = 'sk_test_51PfWtRFJxUP3SBN9D358vWdpw88mBhowCpcrvzALXcxYLGYHn0esmigHqfRgRLtptWUI7Uhok1ee26jAf4MjinsC00bX0UWlSV'

STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', 'pk_test_51PfWtRFJxUP3SBN9C7YE2De9GZPqhJohMeGk0hQLPn3T3QowOS6qayoMtrsG50HHRuhCZhSu4wdsuEHsVtytp3Ds00RNBnMqsw')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_51PfWtRFJxUP3SBN9D358vWdpw88mBhowCpcrvzALXcxYLGYHn0esmigHqfRgRLtptWUI7Uhok1ee26jAf4MjinsC00bX0UWlSV')

# Paystack settings
PAYSTACK_PUBLIC_KEY = 'pk_test_c9791997b436b95b420579a4336e556976ecbef2'
PAYSTACK_SECRET_KEY = 'sk_test_968052c38fff5c9809618bcb5cf55c769aa66cf1'

PAYPAL_CLIENT_ID = 'your_paypal_client_id_here'
PAYPAL_CLIENT_SECRET = 'your_paypal_client_secret_here'

# You can also set the PayPal mode (sandbox or live)
PAYPAL_MODE = 'sandbox'

SNAPSCAN_API_KEY = 'https://pos.snapscan.io/qr/V3ytRu6f'
