# Generated by Django 5.0.6 on 2024-07-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pads_donated', models.PositiveIntegerField(default=0)),
                ('girls_empowered', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Testimony',
        ),
    ]
